### ISSUE TITLE
player names are "(connecting)" after reload

### ISSUE THREAD

**Issue by AssassinTee** [AssassinTee/catch64#29]

**Comment by AssassinTee** [comment]
I don't know how to fix it, looks like a client bug
@Dune-jr pls help 🆘

**Comment by Dune-jr** [comment]
If you think it's a Teeworlds bug, open, an issue on the Teeworlds repo

**Comment by AssassinTee** [comment]
@Dune-jr I found the mistake, it was indeed serversided: I was sending Skinchanges to clients, who aren't ingame (no proof if Server()->ClientIngame() is true).
But i don't know why it broke clients when reloading, can you explain it to me? 

This explains why 0.7.2 or lower clients weren't effected

**Comment by Dune-jr** [comment]
I don't know what causes it.

**Comment by AssassinTee** [comment]
But thank you ^^
